---
- name: Add postgres key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
  sudo: true

- name: Add postgres repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ wheezy-pgdg main' state=present
  sudo: true

- name: install postgresql server
  apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=3600
  sudo: true
  environment: proxy_env
  with_items:
    - postgresql-{{postgresql.version}}
    - postgresql-contrib-{{postgresql.version}}
    - libpq-dev

- name: update postgres client configuration
  sudo: true
  copy: src=pg_hba.conf dest=/etc/postgresql/{{postgresql.version}}/main/pg_hba.conf
