- name: install RVM and Ruby
  shell: curl -sSL https://get.rvm.io | bash -s stable --ruby=2.1
    creates=~/.rvm/rubies/ruby-2.1.1/bin/ruby

- name: Setup defaults for Gem
  copy: src=gemrc dest=~/.gemrc

- name: Add nodejs repo
  apt_repository: repo='ppa:chris-lea/node.js' state=present
  sudo: true

- name: Install nodejs
  apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=3600
  sudo: true
  environment: proxy_env
  with_items:
    - python-software-properties
    - nodejs
