- name: install RVM and Ruby
  shell: curl -sSL https://get.rvm.io | bash -s stable --ruby={{ ruby.version }}
    creates=~/.rvm/rubies/ruby-{{ ruby.version }}/bin/ruby

- name: Setup defaults for Gem
  copy: src=gemrc dest=~/.gemrc

- name: node.js | Make sure that the directory to hold the node.js binaries exists
  sudo: true
  file:
    path: /usr/local/nodejs
    state: directory
    recurse: yes
    mode: 0755

- name: node.js | Download the node.js source
  get_url:
    url: "{{nodejs_url}}"
    dest: "/tmp/node-v{{nodejs_version}}.tar.gz"

- name: node.js | Unpack the node.js source
  shell: tar -xvzf /tmp/node-v{{nodejs_version}}.tar.gz chdir=/tmp creates=/tmp/node-v{{nodejs_version}}

- name: node.js | Get the number of processors
  command: nproc
  register: cpu_count

- name: node.js | Build node.js from source
  shell: >
    cd /tmp/node-v{{nodejs_version}} &&
    PATH="/usr/local/bin:/usr/bin:bin" &&
    ./configure --prefix={{nodejs_prefix}} &&
    sudo make -j {{cpu_count.stdout}} &&
    sudo make install

- name: node.js | Update the symbolic link to the node.js install
  sudo: true
  file:
    path: /usr/local/nodejs/default
    src: "{{nodejs_prefix}}"
    state: link
    force: yes

- name: node.js | Add the node.js binary to the system path
  lineinfile: "{{item}}"
  sudo: true
  with_items:
    - dest=/etc/profile regexp='^NODE_HOME=/usr/local/nodejs/default' line="NODE_HOME=/usr/local/nodejs/default" state=present
    - dest=/etc/profile regexp='^PATH=.*NODE_HOME.*' line="PATH=$PATH:$NODE_HOME/bin" state=present

- name: node.js | Inform the system where node is located and set this one as the default
  shell: "{{item}}"
  sudo: true
  with_items:
    - 'update-alternatives --install "/usr/bin/node" "node" "/usr/local/nodejs/default/bin/node" 1'
    - 'update-alternatives --set node /usr/local/nodejs/default/bin/node'

- name: node.js | Install bower
  sudo: true
  npm: name=bower global=true state=latest executable=/usr/local/nodejs/default/bin/npm
