- name: install RVM and Ruby
  shell: curl -sSL https://get.rvm.io | bash -s stable --ruby={{ ruby.version }}
    creates=~/.rvm/rubies/ruby-{{ ruby.version }}/bin/ruby

- name: Setup defaults for Gem
  copy: src=gemrc dest=~/.gemrc

- name: Remove old nodejs
  apt: pkg=nodejs purge=true
  sudo: true

- name: Install bower
  npm: name=bower state=latest global=true
  sudo: true
